services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=autodb'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
#  redis:
#    image: 'redis:latest'
#    ports:
#      - '6379:6379'
#  mongo:
#    image: 'mongo:latest'
#    ports:
#      - '27017:27017'